apiVersion: apps/v1 
kind: Deployment
metadata: 
  name: MedicineService-deployment
  labels: 
    app: MedicineService
spec:
  replicas: 1 
  selector:
    matchLabels: 
      app: MedicineService
  template:
    metadata:
      labels:
        app: MedicineService
    spec:
      containers:
       - name: azurecontainer2105
        image: azurecontainer2105.azurecr.io/azurecontainerrepo:latest
        ports: 
        - containerPort: 8080
       imagePullSecrets:
       - name: webapisvcsecret
---
apiVersion: v1
kind: Service
metadata: 
  name: MedicineServicesvc
spec:
  type: LoadBalancer
  ports: 
  - port: 80
selector 
 app: MedicineService